name: Build / Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    permissions: write-all
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - os: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/_build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/_build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/_build
      run: ctest -C ${{env.BUILD_TYPE}} -VV
